YSHS_WebSite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
]

YSHS_WebSite/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
    path('common/', include('common.urls'))
]

YSHS_WebSite/mainPage/urls.py
from django.urls import path

from . import views


app_name = 'mainPage'

urlpatterns = [
    path('', views.home, name='home'),
]

YSHS_WebSite/common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission


class CustomUser(AbstractUser):
    grade = models.IntegerField(verbose_name='학년',
                                choices=[(i, f'{i}학년') for i in range(1, 4)],)
    classNum = models.IntegerField(verbose_name='반',
                                   choices=[(i, f'{i}반') for i in range(1, 10)],)
    studentNum = models.IntegerField(verbose_name='출석번호',
                                     choices=[(i, f'{i}번') for i in range(1, 40)],)
    # last_name 사용자 성 : 실명을 뜻함
    # first_name 사용자 이름 - 이미 있음(성은 따로)-실명을 뜻함
    birthDate = models.DateField(verbose_name='생년월일',)
    email = models.EmailField(verbose_name='개인 이메일 주소',
                              unique=True,
                              max_length=254, blank=True, null=True,)
    fAgreeCollectPersonInfor = models.BooleanField(default=False)
    # username 아이디
    # password1 비밀번호1
    # password2 비밀번호 확인

    # chat gpt가 필요하데요
    groups = models.ManyToManyField(
        Group,
        related_name='customuser_set',
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='customuser_set',
        blank=True
    )
    
    

YSHS_WebSite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserForm(UserCreationForm):
    '''
    grade = forms.ChoiceField(choices=[(i, f'{i}st grade') for i in range(1, 4)], label='학년')
    classNum = forms.ChoiceField(choices=[(i, f'class {i}') for i in range(1, 10)], label='반')
    studentNum = forms.ChoiceField(choices=[(i, f'number {i}') for i in range(1, 40)], label='출석번호')
    birthDate = forms.DateField(label='생년월일', widget=forms.SelectDateWidget(years=range(1900, 2100)))
    email = forms.EmailField(label='개인 이메일 주소', required=False)
    # username 아이디
    # password1 비밀번호1
    # password2 비밀번호 확인
    '''
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('grade', 'classNum', 'studentNum', 'birthDate', 'email', 'fAgreeCollectPersonInfor')

YSHS_WebSite/common/views.py
from django.shortcuts import render, redirect # type: ignore
from django.contrib.auth import login, authenticate
from .forms import CustomUserForm
from .models import CustomUser

def signup(request):
    return render(request, 'mainPage/home.html')

def signup(request):
    print(request.method)
    if request.method == "POST":
        form = CustomUserForm(request.POST) # CustomUserForm 사용할거임
        if form.is_valid():
            user = form.save()  # 사용자 생성
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)   # 사용자 인증
            if user is not None:
                login(request, user)    # 로그인 처리
                return redirect('mainPage:home')
    else:
        form = CustomUserForm()
    
    return render(request, 'common/signUp.html', {'form' : form})

YSHS_WebSite/mainPage/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'mainPage/home.html')

YSHS_WebSite/templates/common/login.html
<!doctype html>
<html>
    <head>
        <style>
            header {
                background-color: #fff2ad;
            }
            form {
                width: 600px;
                
            }
        </style>
    </head>
    <body>
        <header>
            <h2>CODEX</h2>
        </header>
        <div>
            <form method="post" action="{% url 'common:login' %}">
                {% csrf_token %}
                <fieldset>
                    <legend>로그인</legend>
                    <br>
                    <label for="id">아이디</label>
                    <br>
                    <input id="id" type="text" name="username"
                    value="{{form.username.value|default_if_none:''}}">
                    <br>
                    <label for="password">비밀번호</label>
                    <br>
                    <input id="password" type="password" name="password"
                    value="{{form.password.value|default_if_none:''}}">
                    <br><br>
                    <input type="submit" value="로그인">
                    <br>
                    <p>회원이 아니신가요?<a href="{% url 'common:signup' %}">  냉@큼 회원가입하기</a></p>
                </fieldset>
            </form>
        </div>
    </body>
</html>

YSHS_WebSite/templates/common/signIn.html
<!doctype html>
<html>
    <head>
        <style>
            header {
                background-color: #fff2ad;
            }
            form {
                width: 600px;
                
            }
        </style>
    </head>
    <body>
        <header>
            <h2>CODEX</h2>
        </header>
        <div>
            <form method="post" action="{% url 'common:login' %}">
                {% csrf_token %}
                <fieldset>
                    <legend>로그인</legend>
                    <br>
                    <label for="id">아이디</label>
                    <br>
                    <input id="id" type="text" name="username"
                    value="{{form.username.value|default_if_none:''}}">
                    <br>
                    <label for="password">비밀번호</label>
                    <br>
                    <input id="password" type="password" name="password"
                    value="{{form.password.value|default_if_none:''}}">
                    <br><br>
                    <input type="submit" value="로그인">
                    <br>
                    <p>회원이 아니신가요?<a href="{% url 'common:signup' %}">  냉@큼 회원가입하기</a></p>
                </fieldset>
            </form>
        </div>
    </body>
</html>

YSHS_WebSite/templates/common/signUp.html
<!doctype html>
<html>
    <head>
        <title>회원가입</title>
    </head>
    <body>
        <header>
            <h1>CODEX</h1>
        </header>
        <div>
            <h3>회원가입</h3>
            <div>
                <!-- 회원가입 폼 시작 -->
                <form method="POST">
                    {% csrf_token %}
                    <fieldset>
                        <legend>개인정보 수집</legend>
                        
                        <!-- 학년 -->
                        {{ form.grade }}
                        <label for="{{ form.grade.id_for_label }}">학년</label>
                        <br>
                        <!-- 반 -->
                        {{ form.classNum }}
                        <label for="{{ form.classNum.id_for_label }}">반</label>
                        <br>
                        <!-- 출석번호 -->
                        {{ form.studentNum }}
                        <label for="{{ form.studentNum.id_for_label }}">번호</label>
                        <br>
                        <!-- 이름 -->
                        {{ form.first_name }}
                        <label for="{{ form.first_name.id_for_label }}">이름</label>
                        <br>
                        <!-- 생년월일 -->
                        {{ form.birthDate }}
                        <label for="{{ form.birthDate.id_for_label }}">생년월일</label>
                        <br>
                        <!-- 이메일 -->
                        {{ form.email }}
                        <label for="{{ form.email.id_for_label }}">개인 이메일 주소</label>
                        <br>
                        <!-- 개인정보 수집 동의 -->
                        {{ form.fAgreeCollectPersonInfor }}
                        <label for='{{ form.fAgreeCollectPersonInfor.id_for_label }}'>개인정보 수집에 동의합니다.</label>
                        <!--
                        <label for="agree_terms">개인정보 수집에 동의합니다.</label>
                        <input type="checkbox" id="agree_terms" name="agree_terms" required>
                        -->
                    </fieldset>
                    
                    <!-- 아이디 -->
                    {{ form.username }}
                    <label for="{{ form.username.id_for_label }}">아이디 (닉네임으로 표시됩니다.)</label>
                    <br>
                    <!-- 비밀번호 -->
                    {{ form.password1 }}
                    <label for="{{ form.password1.id_for_label }}">비밀번호</label>
                    <br>
                    <!-- 비밀번호 확인 -->
                    {{ form.password2 }}
                    <label for="{{ form.password2.id_for_label }}">비밀번호 확인</label>
                    <br>
                    <br><br>
                    <!-- 제출 버튼 -->
                    <button type="submit">회원가입</button>
                </form>
            </div>
        </div>
    </body>
</html>

YSHS_WebSite/templates/mainPage/home.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>Codex test area</title>
        <style>
            header {
                background-color: #fff2ad;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>CODEX</h1>
            <ul>
                <li><a href="{% url 'common:login' %}">로그인</a></li>
            </ul>
        </header>
    </body>
</html>

YSHS_WebSite/templates/mainPage/mainPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MainPage</title>
</head>
<body>
    <h1>MainPage</h1>
    <h6>여기는 프로트엔드 업무임!!</h6>
</body>
</html>